# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-20.04

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
# 
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - task: Docker@2
            displayName: build docker image
            inputs:
              command: build
              containerRegistry: container registry
              repository: contosoRepository
              tags: dev-$(Build.BuildId)
          - task: Docker@2
            displayName: log in to container registry
            inputs:
              command: login
              containerRegistry: acr-morphicdev
          - task: Docker@2
            displayName: push docker image
            inputs:
              command: build
              containerRegistry: container registry
              repository: contosoRepository
              tags: dev-$(Build.BuildId)
          - task: Docker@2
            displayName: log out of container registry
            inputs:
              command: logout
              containerRegistry: acr-morphicdev

